"""empty message

Revision ID: 6a94b7e7f2b1
Revises: a91e611c14bd
Create Date: 2021-03-30 15:55:09.869340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a94b7e7f2b1'
down_revision = 'a91e611c14bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'upvote_count')
    op.drop_column('post', 'downvote_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('downvote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('upvote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
