"""empty message

Revision ID: 8c616daa94ef
Revises: a2eb6448c329
Create Date: 2021-04-05 17:35:46.182210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c616daa94ef'
down_revision = 'a2eb6448c329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'image')
    op.drop_column('order', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
