"""empty message

Revision ID: f73062396d7d
Revises: 6a94b7e7f2b1
Create Date: 2021-03-30 17:18:07.723493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73062396d7d'
down_revision = '6a94b7e7f2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'upvote_count')
    op.drop_column('comment', 'downvote_count')
    op.add_column('user', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('zip', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'address')
    op.add_column('comment', sa.Column('downvote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('upvote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
